# version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream-xtube-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - .:/app
      - ./storage:/app/storage
      - ./bootstrap/cache:/app/bootstrap/cache
      - /etc/letsencrypt:/etc/letsencrypt:ro
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
